CREATE SYNONYM [dbo].SYSAccount FOR [BIFramework].[dbo].SYSAccount
CREATE SYNONYM [dbo].SYSApp FOR [BIFramework].[dbo].SYSApp
CREATE SYNONYM [dbo].SYSMenu FOR [BIFramework].[dbo].SYSMenu
CREATE SYNONYM [dbo].SYSAppAccess FOR [BIFramework].[dbo].SYSAppAccess
CREATE SYNONYM [dbo].SYSAttach FOR [BIFramework].[dbo].SYSAttach
CREATE SYNONYM [dbo].SYSDept FOR [BIFramework].[dbo].SYSDept
CREATE SYNONYM [dbo].SYSFilter FOR [BIFramework].[dbo].SYSFilter
CREATE SYNONYM [dbo].SYSGroup FOR [BIFramework].[dbo].SYSGroup
CREATE SYNONYM [dbo].SYSGroupUser FOR [BIFramework].[dbo].SYSGroupUser
CREATE SYNONYM [dbo].SYSLog FOR [BIFramework].[dbo].SYSLog
CREATE SYNONYM [dbo].SYSOperation FOR [BIFramework].[dbo].SYSOperation
CREATE SYNONYM [dbo].SYSOperationFilter FOR [BIFramework].[dbo].SYSOperationFilter
CREATE SYNONYM [dbo].SYSPassport FOR [BIFramework].[dbo].SYSPassport
CREATE SYNONYM [dbo].SYSPosition FOR [BIFramework].[dbo].SYSPosition
CREATE SYNONYM [dbo].SYSStrategy FOR [BIFramework].[dbo].SYSStrategy
CREATE SYNONYM [dbo].SYSStrategyGroup FOR [BIFramework].[dbo].SYSStrategyGroup
CREATE SYNONYM [dbo].SYSStrategyOperation FOR [BIFramework].[dbo].SYSStrategyOperation
CREATE SYNONYM [dbo].SYSSystem FOR [BIFramework].[dbo].SYSSystem
CREATE SYNONYM [dbo].SYSSystemCertificate FOR [BIFramework].[dbo].SYSSystemCertificate
CREATE SYNONYM [dbo].SYSTag FOR [BIFramework].[dbo].SYSTag
CREATE SYNONYM [dbo].SYSTagApply FOR [BIFramework].[dbo].SYSTagApply
CREATE SYNONYM [dbo].SYSTagAuthority FOR [BIFramework].[dbo].SYSTagAuthority
CREATE SYNONYM [dbo].SYSTagClass FOR [BIFramework].[dbo].SYSTagClass
CREATE SYNONYM [dbo].SYSTagLogs FOR [BIFramework].[dbo].SYSTagLogs
CREATE SYNONYM [dbo].SYSTagTarget FOR [BIFramework].[dbo].SYSTagTarget
CREATE SYNONYM [dbo].SYSToken FOR [BIFramework].[dbo].SYSToken
CREATE SYNONYM [dbo].vw_SYSTag FOR [BIFramework].[dbo].vw_SYSTag
CREATE SYNONYM [dbo].vw_SYSTagGroup FOR [BIFramework].[dbo].vw_SYSTagGroup